version: "3.8"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend-build:/usr/share/nginx/html
      - ./attached_assets:/usr/share/nginx/html/attached_assets
    ports:
      - "80:80"
    depends_on:
      - resume-app
      - frontend-builder
    restart: unless-stopped
    networks:
      - app-network

  frontend-builder:
    build: 
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - frontend-build:/shared
    command: ["sh", "-c", "cp -r /app/dist/public/* /shared/ && echo 'Frontend build copied to shared volume'"]
    networks:
      - app-network

  resume-app:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DOMAIN=russeltagaca.com
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      # Mount the PDF file directory
      - ./attached_assets:/app/attached_assets:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/test || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

volumes:
  frontend-build:

networks:
  app-network:
    driver: bridge
