api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  port170:
    address: ":170"
  traefik:
    address: ":8080"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: INFO

accessLog: {}